#align(center)[= MATH4069 Notes]
#align(center)[=== Measure Theory and Fourier Transform (Advanced)]

== Measurable Sets
#text(weight: "bold")[Definition 1]: $sigma$-algebra\
$cal(A)$ is said to be a $sigma$-algebra of X, are a collection of subsets of X that satisfy:
- Empty set: $emptyset in cal(A)$
- Closure under compliments: $A in cal(A) => A^c in cal(A)$
- Closed under unions: $A_j in cal(A) => union_(j in NN) A_j in cal(A)$
#underline[Example]:
A set $cal(A)$ is a $sigma$-algebra, show that $cal(A)_S := {A inter S: A in cal(A)}$ is a $sigma$-algebra of S.
1. $emptyset in cal(A)_S$ since $emptyset in cal(A) => S inter emptyset in cal(A)_S$
2. Let $B in cal(A)_S => B := A inter S => B^c := S without B = A^c inter S in cal(A)_S because A^c in cal(A)$
3. Let ${B_j} in cal(A)_S => forall j in NN B_j := A_j inter S$ then, $union.big B_j = union.big A_j inter S =
S inter union.big A_j in cal(A)_S because union.big A_j in cal(A)$
\
#text(weight: "bold")[Definition 2]: Measure\
A function $mu: cal(A) -> [0, infinity]$ is called a measure if:
- Empty set: $mu(emptyset) = 0$
- Countable addivity: $A_j in cal(A)$ are disjoint, then $mu(union_(j in NN) A_j) = sum_(j=1)^(infinity) mu(A_j)$
#underline[Example]:
A function $mu: cal(A) -> [0, infinity]$ is a measure. Show that $mu_S(A) := mu(A inter S)$ is also a measure.
1. $mu_S (emptyset) = mu(emptyset inter S) = mu(emptyset) = 0$
2. $mu_S (union.big A_j) = mu((union.big A_j) inter S) = mu(union.big (A_j inter S)) = sum mu(A_j inter S) = sum mu_S (A_j)$
\
#text(weight: "bold")[Definition 3]: Outer Measure\
A function $mu^*: cal(P)(x) -> [0, infinity]$ is called an outer measure if:
- Empty set: $mu^*(emptyset) = 0$
- Countable sub-addivity: $A, A_j in cal(A)$, with $A subset.eq union_(j=0)^(infinity) A_j$ then $mu^*(A) <= sum_(j=1)^(infinity) mu^*(A_j) $\
\
#text(weight: "bold")[Definition 4]: Lebesgue Outer Measure\
The function $m_(N)^*$ is called the Lebesgue Outer Measure and is defined on $RR^N$ as:
$ m_N^* := inf{sum_(k=0)^(infinity) "vol"(R_k) : A subset.eq union.big_(k=0)^(infinity) R_k, R_k " open rectangles" } $
An open rectangle $R_k in RR^N$ can be defined as $R_k = (a_0, b_0) times ... times (a_N, b_N)$, this means that the
 volume is defined as
$ "vol"(R_k) = (b_1 - a_1)...(b_N - a_N) $
\
#text(weight: "bold")[Definition 5]: Measurable Sets\
A set $A subset.eq X$ is said to be measurable, with respect to a measure (or outer measure) $mu$ (or $mu^*$) if for a
generic set $S subset.eq X$ it satisfies
$ mu^*(S) = mu^*(S inter A) + mu^*(S inter A^c) $
\
#text(weight: "bold")[Definition 6]: Lebesgue Measure\
The Lebesgue Measure, $m_N^*$ on $RR^N$ is defined as
Since the Lebesgue Measure is a Borel Measure, all open and closed sets are automatically measurable. All countable
unions/intersections of closed and open sets are measurable.\
\
#text(weight: "bold")[Definition 7]: Borel Sets\
A Set $B$ is said to be Borel if for the collection of all open sets in X, $C$, $B$ is generated by $cal(A) (C)$. In
general, we say that the following sets are Borel:
- all open sets (definition)
- all closed sets (compliment of open sets)
- all countable unions/intersections of open/closed sets (closure under unions)
- all countable unions/intersections of Borel sets\

== Measurable Functions
#text(weight: "bold")[Definition 1]: Measurable Functions\
A function $f: X -> KK^N$ is said to be measurable if for all open sets $U subset.eq KK^N$, $f^(-1) [U] in cal(A)$.\
Remark:
- f is measurable if and only if $f^(-1) [B] in cal(A)$ for every Borel set $B in KK^N$
- $f:X -> R$ is measurable if and only if $f^(-1)((alpha, infinity)) in cal(A)$ for every rational $alpha in RR$
- All continous functions are Borel Measurable\
\
#text(weight: "bold")[Definition 2]: Indicator Functions\
An indicator function is defined with a set $A subset.eq X$ with
$ 1_A: X -> RR (x) = cases(
    1 "if" x in A,
    0 "if" x in.not A,
) $
Remark: The indicator function is measurable if and only if the set $A$ is measurable.\
\
#text(weight: "bold")[Definition 3]: Simple Functions\
A simple function can be defined as a weighted sum of indicator functions, where ${A_k} in X$ are disjoint and $alpha_k in RR$
$ f(x) = sum_(k=1)^(m) alpha_k 1_(A_k)(x) $
\
#text(weight: "bold")[Definition 4]: Positive Measurable Functions\
For every measurable function $f:X -> [0, infinity]$ there exists a sequence of simple measurable functions $phi_n: X->[0, infinity)$
such that $0<=phi_n <= phi_(n+1) <= f$ for all $n in NN$ and $lim_(n->infinity) phi_n (x) = f(x)$ for all $x im X$\
Remark: We can utilise the Monotone Convergence Thereom to prove that a function is integrable.
#underline[Example]:
For a measurable function $g:X->[0, infinity]$, $nu (A) := integral_A g d mu := integral_X g 1_A d mu$, prove that
$integral_X f d nu = integral_X f g d mu$ by starting with simple measurable, then positive and finally real-valued functions.
1. If f is simple then $f := sum_k alpha_k A_k$ and $integral_X f d nu = sum_k alpha_k nu(A_k) = sum_k alpha_k
integral_A_k g d mu = integral_X sum_k alpha_k 1_(A_k) g d mu = integral_X f g d mu$
2. If f is positive, then $exists phi_n$ simple such that $phi_n -> f$ then $integral_X f d nu = lim_(n->infinity) integral_X
phi_n g d mu = integral_X lim_(n->infinity) phi_n g d mu = integral_X f g d mu$
3. If f is real valued, then $f = f^+ - f^-$ where both $f^+$ and $f^-$ are positive functions, then $integral_X f d nu
= integral_X f^+ d nu - integral_X f^- d nu = integral_X f^+ g d mu - integral_X f^- g d mu = integral_X f g d mu$\
\
== Integration
#text(weight: "bold")[Definition 1]: Integration of Simple Functions\
If $phi: X -> [0, infinity) = sum_(k=0)^n alpha_k A_k$ is a positive, simple, measurable function then we can define the
integral of $phi$ as:
$ integral_X phi(x) d mu = sum_(k=0)^n alpha_k mu(A_k) $
Remark: The following are properties of the Integration of Measurable Functions:
- Addition: $integral_X phi + psi d mu = integral_X phi d mu + integral_X psi d mu$
- Projection: $integral_X alpha phi d mu = alpha integral_X phi d mu$
- Monotonicity: for $0<=phi<=psi$, $0<=integral_X phi d mu <= integral_X psi d mu$\
\
#text(weight: "bold")[Definition 2]: Monotone Convergence Theorem\
For a sequence of functions $f_n : X -> [0, infinity]$, with $0<=f_n <= f_(n+1), forall n in NN$ then,
$ lim_(n->infinity) integral_X f_n d mu = integral_X lim_(n->infinity) f_n d mu = integral_X f d mu $
This theorem provides us the neccessary conditions to pass a limit through an integral.\
\
#text(weight: "bold")[Definition 3]: Fatou's Lemma\
Let $f_n : x -> [0, infinity]$ be an arbitrary measurable function, then
$ integral_X liminf_(n->infinity) f_n d mu <= liminf_(n->infinity) integral_X f_n d mu $
\
#text(weight: "bold")[Definition 4]: Integrability\
A function $f: X-> KK$ is said to be integrable, or $f in cal(L)^1 (X)$ if
$ integral_X abs(f) d mu < infinity $
\
#text(weight: "bold")[Definition 5]: Dominated Convergence Theorem\
On a measure space $(X, cal(A), mu)$, a series of functions $f_n: X -> KK$ are measurable functions such that $f_n -> f$
and if there exists a $g in cal(L)^1 (X)$ such that $abs(f_n) <= g$ for all $n in NN$, then we can say
$ lim_(n->infinity) integral_x f_n d mu = integral_x lim_(n->infinity) f_n d mu = integral_x f d mu $

#text(weight: "bold")[Definition 6]: Continuity of Parameter Integrals\
If the function, $f: X times Y -> KK$, satifies the following conditions:
- $x -> f(x, y)$ is measurable for all y
- $y -> f(x, y)$ is continuous for all x
- $exists g in L^1 (X;RR)$ such that $abs(f(x,y)) <= g(x)$
Then we can say that
$ F(y) := integral_X f(x,y) d mu $ is continuous at y\
\
#text(weight: "bold")[Definition 7]: Differentiation of Parameter Integrals\
If the function, $f: X times Y -> KK$, satifies the following conditions:
- $x -> f(x,y)$ is integrable
- $(delta f)/(delta y)$ exists and is continuous
- $exists g in L^1 (X;RR)$ such that $abs((delta f)/(delta y)) <= g(x)$
Then for a function $F(y) := integral_X f(x,y) d mu$, we can define the derivative of $F$ as:
$ F'(y) := integral_X (delta f)/(delta y) d mu $
\
#text(weight: "bold")[Definition 8]: p-Lebesgue Measure\
We can define the function $||.||_p$ as $||u||_p := (integral_X abs(u)^p d mu) ^(1/p)$ and the L-p space as follows
$ cal(L)^p (X) = {f:X ->KK " measurable": ||u||_p < infinity} $
We can then define a space $L^p := cal(L)^p without cal(N) (X)$ where $cal(N) (X)$ is the set of zero almost everywhere functions on X.
\
#text(weight: "bold")[Definition 9]: Inequalities of Integrals\
1. Holder's Inequality: $|integral_X f g d mu| <= integral_X abs(f g) d mu <= ||f||_p ||g||_q s.t. (1/p) + (1/q) = 1$
2. Minkowski's Inequality (Triangle Inequality): $||f + g||_p <= ||f||_p + ||g||_p$\
\
#text(weight: "bold")[Definition 10]: Tonelli's Theorem\
Tonelli's Theorem applies to positive function $f: X times Y -> [0, infinity]$ and states that if:
- x -> f is measurable
- y -> f in measurable
- x -> $integral_Y f d y$ is measurable
- y -> $integral_X f d x$ is measurable
Then we can say that $integral_X integral_Y f d y d x = integral_Y integral_X f d x d y$\
\
#text(weight: "bold")[Definition 11]: Fubini's Theorem\
Fubini's Theorem applies to any function $f: X times Y -> KK$ and states that if:
- $integral_X integral_Y abs(f) d y d x$ or $integral_Y integral_X abs(f) d x d y$ are finite
- x -> f is measurable
- y -> f in measurable
- x -> $integral_Y f d y$ is measurable
- y -> $integral_X f d x$ is measurable
Then we can say that $integral_X integral_Y f d y d x = integral_Y integral_X f d x d y$\
\
== Convolutions and Fourier Transforms
#text(weight: "bold")[Definition 1]: Convolution\
If $f, g: RR^N -> K$ are measurable functions, then we can define the convolution of $f * g$ as
$ (f*g)(x) = integral_(RR^N) f(x-y)g(y) d y $
\
#text(weight: "bold")[Definition 2]: Young's Inequality\
For two functions, $f in L^1$ and $g in L^p$ and $f*g in L^p$, then
$ ||f*g||_p <= ||f||_1 ||g||_p  $
Moreover, if $f in L^p$ and $g in L^q$ and $(1/p) + (1/q) = 1$, then
$ ||f*g||_(infinity) <= ||f||_p ||g||_q $
\
#text(weight: "bold")[Definition 3]: Approximate Identity\
A function $phi in L^1$ is an approximate identity if
$ integral_(RR^N) phi d x = 1 $
Then for $phi_h := (1/h^N) phi(x/h)$ we can say that:
- For $f in L^p$, $f*phi_h -> f$ in $L^p$ as $h->0$
- If f is continous at $x_0$, then $f*phi_h (x_0) -> f (x_0)$ as $h -> 0$
- $phi$ is bounded above by $(C)/(1 + abs(x)^(N+alpha))$, for $C, alpha > 0$
\
#text(weight: "bold")[Definition 4]: Fourier Transform\
The Fourier Transform of a function $f in L^1$, denoted by $limits(f)^hat$ is defined as
$ limits(f)^hat = integral_(RR^N) f(x) e^(- 2 pi i x.t) d x $
\
#text(weight: "bold")[Definition 5]: Riemann-Lebesgue Lemma\
$limits(f)^hat in C_0 (RR^N) := {f in C(RR^N): lim_(abs(x) -> infinity) f(x) = 0}$ for all $f in L^1$, meaning
that $limits(f)^hat$ is continous and $limits(f)^hat -> 0 "as" abs(t) -> infinity$
\
#text(weight: "bold")[Definition 6]: Gaussian identity for the Fourier Transform\
Let $phi(x) = e^(- pi abs(x)^2)$ be the fixed point such that $phi^hat = phi$. More generically, we can then
define a function $psi_c (x) = e^(-c abs(x)^2)$ and its Fourier Transform as,
$ psi^hat_c (t) = (pi/c)^(N/2) phi(sqrt(pi/c) t) $
\
#text(weight: "bold")[Definition 7]: Fourier Inversion Formula\
The Fourier Inversion Formula for $f in L^1$, relies on the convolution,
$ (f * psi_epsilon) (x) = integral_(RR^N) f^hat (t) phi_epsilon (t) e^(2 pi i x t) d t $
With a special case where $phi (t) = e^(- pi abs(x)^2)$ and $phi_epsilon(t) = 1/epsilon^N phi(t/epsilon)$ we can say that
$ (f * psi_epsilon) (x) -> f$
If both $f, f^hat in L^1$, then by the dominated convergence theorem, we can say that
$ f(x) = integral_(RR^N) hat(f) (t) e^(2 pi i x t) d t $
